### ISSUE TITLE
Search algos not responsive

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#1]
The searching algorithm is not responsive and does not fit the screen on mobile screen.

**Comment by jainaayush01** [comment]
Hello @akshitadixit,
Please assign this issue to me.
Proposed Changes:
![image](https://user-images.githubusercontent.com/54480934/106364435-fabc9e00-6354-11eb-98a6-55dea67a2f18.png)
![image](https://user-images.githubusercontent.com/54480934/106364461-2c356980-6355-11eb-81fd-bd48112bcaff.png)

Other Changes I Have made:
Added some Issues that I will be working on in WOC IIIT-Kalyani/Timeline.md
Improved codebase readability
Changed Structure and Style of Sorting and Searching Page by removing unnecessary div elements and making it more responsive and look better.

Let me know if any changes are there or I made a mistake by removing those elements.

**Comment by akshitadixit** [comment]
Hey @jainaayush01 this looks good to go. Except in the navigation bar, the highlighted menu item should be on the current page rather than the Home page. With reference to other changes, please go ahead and make a PR.

**Comment by jainaayush01** [comment]
Okay Thanks.
