### ISSUE TITLE
Add Speed and Number of bars to the Sorting Visualizer

### ISSUE THREAD

**Issue by jainaayush01** [akshitadixit/Structurex#13]

**Comment by jainaayush01** [comment]
I would like to work on this issue. Please assign this to me

**Comment by akshitadixit** [comment]
Sure. But did you activate gh-pages on your repo? Please do that so it is easier for me to view changes.

**Comment by jainaayush01** [comment]
Yes i had activated the gh-pages but that branch was deleted.
now i have changed the branch. Sorry for the inconvenience caused.
