### ISSUE TITLE
Minute changes needed

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#20]
- [x] Website title needs to be changed
- [x] Project logo needs to be added somewhere if possible

**Comment by mtwn105** [comment]
Opened PR for 1st point

**Comment by Sakalya100** [comment]
@akshitadixit Can I work on the left over issue that is project logo?

**Comment by akshitadixit** [comment]
@Sakalya100 thank you for pointing out but that has been done too.
