### ISSUE TITLE
Search features

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#21]
- [ ] Add speed and no. of bars in search.html
- [x] Randomize the numbers in the array
- [x] Fix alignment of the text as shown below 
![image](https://user-images.githubusercontent.com/56997545/109409366-1c429100-79b8-11eb-9a85-fc9787d9cc96.png)

- [ ] (**Advanced**) Let user enter the array to be searched

Create a PR with at least one of these issues solved and -[x] the solved issue(s)

**Comment by mtwn105** [comment]
Hi @akshitadixit 

Fixed the alignment issue. Opened the PR.

![image](https://user-images.githubusercontent.com/12975481/109409694-de933780-79ba-11eb-8793-9c9906ced22a.png)

**Comment by akshitadixit** [comment]
Thanks @mtwn105

**Comment by jainaayush01** [comment]
I would like to work on 2nd Issue
