### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#22]
Need a home/landing page (currently index.html is set as the sorting page)

**Comment by shivshankar9** [comment]
i want to add landing page(home page)

**Comment by akshitadixit** [comment]
Sure

**Comment by shivshankar9** [comment]
Issue solved in  #29 PR

**Comment by akshitadixit** [comment]
@shivshankar9 sorry for the trouble but can you make the PR again, I mistakened it for an issue and closed it unfortunately :(

**Comment by shivshankar9** [comment]
Yes sure
