### ISSUE TITLE
Sorting buttons

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#23]
Buttons in sorting page needs to be reduced in size so as to accommodate them in a single line

**Comment by akshitadixit** [comment]
@shivshankar9  would you like to take this up?

**Comment by shivshankar9** [comment]
okay  i will do.

**Comment by shivshankar9** [comment]
oversized buttons i think already fixed please checkout..

**Comment by akshitadixit** [comment]
> oversized buttons i think already fixed please checkout..

Please let me know where?

**Comment by shivshankar9** [comment]
![Screenshot (169)](https://user-images.githubusercontent.com/69760883/109764076-0d0e4e00-7c19-11eb-9dba-733da01d2a15.png)
As you can check first button and last three buttons reduced in size, if still oversized not fixed let me i will work that.
