### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by harshita0802goswami** [akshitadixit/Structurex#36]
A footer will be added with a suggestion form and contact details

**Comment by akshitadixit** [comment]
@harshita0802goswami assigned :)

**Comment by harshita9621** [comment]
@akshitadixit Can I work on this issue

**Comment by akshitadixit** [comment]
@harshita0802goswami are you done or do we assign to @harshita9621 ?

**Comment by harshita0802goswami** [comment]
I am working on this issue, making PR in an hour
