### ISSUE TITLE
Add code for sorting algorithms 

### ISSUE THREAD

**Issue by harshita0802goswami** [akshitadixit/Structurex#38]
Whenever a person clicks on bubble sort or any other sorting searching method, it will show the relevant program for that option

**Comment by akshitadixit** [comment]
@harshita0802goswami please add a relevant example or screenshot of what you wish to achieve before I assign this to you

**Comment by lokeshrepaka** [comment]
Can you assign any task to me

**Comment by akshitadixit** [comment]
Hey @lokeshrepaka please create an issue or ask for an unassigned issue :)

**Comment by TheArushiSingh** [comment]
Can I and @harshita0802goswami work on this issue together? 
if she's ready to team up

**Comment by akshitadixit** [comment]
@TheArushiSingh sure, open source is all about collaboration :) it is highly encouraged to work together.

However this [statement](https://github.com/akshitadixit/Structurex/issues/38#issuecomment-871172244) needs clarification before I can proceed to assign.

**Comment by harshita0802goswami** [comment]
For an instance, if a user clicks on bubble sort, then a new page will open in which there will be a program of bubble sort

**Comment by harshita0802goswami** [comment]
> Can I and @harshita0802goswami work on this issue together?
> if she's ready to team up

Yes sure :)

**Comment by akshitadixit** [comment]
> For an instance, if a user clicks on bubble sort, then a new page will open in which there will be a program of bubble sort

what if instead of an entirely new page, we let the code appear on the same page, a little lower? Like a pop-up or something, or just a centered div? Just an idea. What do you think @harshita0802goswami @TheArushiSingh

**Comment by TheArushiSingh** [comment]
Yeah good idea!
We will work on that

**Comment by harshita0802goswami** [comment]
Are you saying like if we hover over the text it will show a pop up kind of msg in which the program will be written?

**Comment by TheArushiSingh** [comment]
We can divide that pop-up window into 2 columns
Left side will show the explanation of the algorithm and right side will show the code.
What's say?

**Comment by harshita0802goswami** [comment]
Hi Arushi, would you pls send me a msg on slack so that we can discuss this and work together? :)

**Comment by akshitadixit** [comment]
Even better! 

Before making the PRs do mention here which one of you will do which part.

**Comment by harshita0802goswami** [comment]
yeah, let's discuss this on slack

**Comment by lokeshrepaka** [comment]
Yes I like this can I also work with you. @akshitadixit can I work with them

**Comment by akshitadixit** [comment]
@lokeshrepaka sure I have no issues

**Comment by lokeshrepaka** [comment]
@harshita0802goswami any issues for u

**Comment by TheArushiSingh** [comment]
@harshita0802goswami  I've texted you on slack! 🙂

**Comment by harshita0802goswami** [comment]
> @harshita0802goswami any issues for u

not at all

**Comment by TheArushiSingh** [comment]
@lokeshrepaka  can you text us on slack?

**Comment by lokeshrepaka** [comment]
Done
