### ISSUE TITLE
Add link to read more about algorithms 

### ISSUE THREAD

**Issue by TheArushiSingh** [akshitadixit/Structurex#39]
When the user clicks on any one of these options he should be directed to a page which provides following information: 
1.  Explanation of the algorithm 
2.  Code of that algorithm in C++,Java and  Python 
![more info](https://user-images.githubusercontent.com/42888907/123921218-65294700-d9a4-11eb-9155-9162135bb473.JPG)

I would like to work on this issue. 
Pls assign it to me.

**Comment by akshitadixit** [comment]
Please consider the request made in #38
