### ISSUE TITLE
Improvising README.md

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#40]
The readme looks very plain as of now, would like it to be improvised.

**Comment by harshithatnbr** [comment]
@akshitadixit  I would like to work on this issue. Please assign it to me

**Comment by akshitadixit** [comment]
@harshithatnbr sure :)

**Comment by harshithatnbr** [comment]
@akshitadixit I am new to Open Source. Can you let me know how to add my name to contributors section? Thankyou.

**Comment by akshitadixit** [comment]
Hey @harshithatnbr the updated contributors will be shown in a few hours. It is automatic but has a bit of latency.
