### ISSUE TITLE
Data set is changing after giving input in searching page.

### ISSUE THREAD

**Issue by harshithatnbr** [akshitadixit/Structurex#43]
- **This is the data set before giving the element to be searched.**

![image1](https://user-images.githubusercontent.com/56475512/124071021-61f19200-da5c-11eb-9094-7b9d9c0f9c45.png)

- **This is the data set on which  search is being performed. Data set is changing after giving input .** On the new data set linear search is being performed. This is same the case with Binary Search.
![image2](https://user-images.githubusercontent.com/56475512/124071147-8ea5a980-da5c-11eb-9991-33abc68467f2.png)

This leads to confusion and results will be unpredictable.
I would like to work and rectify this issue. Please assign it to me under DCP 2021.
Thankyou.

**Comment by akshitadixit** [comment]
@harshithatnbr sure, good one!
