### ISSUE TITLE
Diameter of a Binary Tree 

### ISSUE THREAD

**Issue by neha030** [akshitadixit/Structurex#44]
I want  to provide C++ code for diameter of a binary tree .
Please assign me this issue.

**Comment by akshitadixit** [comment]
@neha030 that's great, but please see that your issue has little or nothing to do with the project. This is about visualization of your algorithms and not just providing code. 

Also we aren't dealing with c++, rather this repo is entirely based on JavaScript, HTML and CSS. Please be considerate enough to go through the repository and it's code before deciding to raise issues in your "comfort zone". 

What you could do however is cloning the repo on local and trying to see if you find any bugs, or if you want to improve something, or even better if you wish to implement a visualization on your own. I hope you take the feedback positively in the true spirit of open source.

**Comment by neha030** [comment]
Sure , I will go through the project and then try to contribute
