### ISSUE TITLE
Add values over the array bars in sorting

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#45]
![image](https://user-images.githubusercontent.com/56997545/124213740-b8b7a400-db0e-11eb-9c97-5da186275160.png)
It would be nice if the array bars had their values written over them so it becomes easier to track and compare values on the user end.

**Comment by harshithatnbr** [comment]
I would like to work on this issue. Please assign to me.

**Comment by akshitadixit** [comment]
Sure :)
