### ISSUE TITLE
Add Contact Us section in your website and also the links to the social-media 

### ISSUE THREAD

**Issue by K-jais** [akshitadixit/Structurex#47]
Adding the contact us section to your website gives the users the feature to discuss anything about the website with the admins and the caretakers of the website.

**Comment by akshitadixit** [comment]
@K-jais thanks for the suggestion. Assigning.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by akshitadixit** [comment]
@purohitmansi glad that you wish to contribute. However @K-jais has already made a PR for the same.

**Comment by purohitmansi** [comment]
Okay
