### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by Swastik1710** [akshitadixit/Structurex#48]
The website doesn't have a Footer section as of now.
I would like to add one for it if you want.
It would contain some social media links ,links to other pages on the website and a copyright text too.

**Comment by akshitadixit** [comment]
Checkout #36

**Comment by Swastik1710** [comment]
Totally missed it.
My bad

**Comment by akshitadixit** [comment]
It's fine @Swastik1710 you can however connect with @harshita0802goswami to see if you can collaborate with her.
