### ISSUE TITLE
Updating readme.md file 

### ISSUE THREAD

**Issue by PrathmeshMutke** [akshitadixit/Structurex#51]
I want to add extra appearance to readme file 
Please assign me 
Devincept 21

**Comment by akshitadixit** [comment]
@PrathmeshMutke kindly elaborate on what you wish to add.

**Comment by PrathmeshMutke** [comment]
I want to add tech stack images and licence gif to readme file to make nice appearance

**Comment by akshitadixit** [comment]
Assigned :)
