### ISSUE TITLE
Modification with Hero Section

### ISSUE THREAD

**Issue by 2024-SANDHYA** [akshitadixit/Structurex#53]
Want to modify the hover effects of the header and adding an introduction in the hero section also adding a footer to the website.

**Comment by akshitadixit** [comment]
#36 please check that the footer has an issue assigned.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> #36 please check that the footer has an issue assigned.

Ok , but I would love to modify the hero section, so instead of the footer I wanna work with the hero section of the website

**Comment by akshitadixit** [comment]
Sure :)
