### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [akshitadixit/Structurex#57]
I would like to add contribution guidelines for beginners in open source. Please assign this to me .

**Comment by Ayushparikh-code** [comment]
> I would like to add contribution guidelines for beginners in open source. Please assign this to me .

hey @swathi-469 contribution guidelines are already available in readme of repo  !

**Comment by swathi-469** [comment]
yes mam I would like to add a separate file containing links, resources to be downloaded along with a link, screenshots for fork , pull , clone and so on.

**Comment by swathi-469** [comment]
Mam What happened may I know what is the invalid label.

**Comment by akshitadixit** [comment]
@swathi-469 you can drop the mam. The issue is invalid because we already have these guidelines and no extra files are needed.
