### ISSUE TITLE
Organize repo

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#6]
The files have been carelessly placed, need to organize the repo, put files in respective folders and simultaneously change their path references in the code to the new path.

**Comment by shivshankar9** [comment]
i want to work on this, assigne me..

**Comment by akshitadixit** [comment]
Hey @shivshankar9  please inform how you wish to achieve this, then i will assign it to you

**Comment by shivshankar9** [comment]
Structure should look like:
Folders:
1.temp
2. WOC IIIT Kalyani
3. src
 - 3.1 assets
    --- 3.1.1  logo.png 
 - 3.2 css
    - 3.2.1 style.css
 - 3.3 JS
   - 3.3.1all the  .js files
4. liscense
5. index.html
6. Readme.md

**Comment by akshitadixit** [comment]
Assigned.
