### ISSUE TITLE
User Insertion

### ISSUE THREAD

**Issue by Shivani13121007** [akshitadixit/Structurex#63]
It will be great if user can enter his own array and can perform sorting on it's own entered array.
I want to add this feature.

**Comment by akshitadixit** [comment]
Yeah, seem like a good issue.

**Comment by Shivani13121007** [comment]
But Implementing every sorting algorithms takes lot of time.
Can I implement only 2 right now?

**Comment by Shivani13121007** [comment]
Done with my task. Please Review it.
So that I can make PR
https://user-images.githubusercontent.com/68291301/125815331-78e279a6-f1bb-4435-b815-6ad546db9c2b.mp4

**Comment by akshitadixit** [comment]
Hey @Shivani13121007 that looks good. However instead of adding it to another different page, who don't you let the user choose between random values and his own input values on the sort.html page?

**Comment by Shivani13121007** [comment]
I keep it in a separate page because it will not look gud that user can enter array only for two sorting techniques 
I mean to say that this will create confusion to user that only bubble or selection sort is working for his own array and others are not

**Comment by Shivani13121007** [comment]
do reply
Should i make PR ?

**Comment by akshitadixit** [comment]
@Shivani13121007 you can make it into the same page nevertheless and create an issue for the rest, so someone else might come and solve it.

**Comment by amitpant14** [comment]
@akshitadixit Can I add this functionality for the other algorithms if it is not being worked upon currently?
