### ISSUE TITLE
Non-uniform UI

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#70]
THe page looks weird right now, not very responsive as well.

**Comment by everly-gif** [comment]
I can work on this, please assign it to me.

Are we talking about the home page alone or the other pages as well?

**Comment by akshitadixit** [comment]
The home page alone. You can create new issues for other pages if you wish.

**Comment by everly-gif** [comment]
great then I can work on it!

**Comment by biohazard2117** [comment]
@akshitadixit I can work on this .. Will you please assign it to me ?

**Comment by akshitadixit** [comment]
@biohazard2117 sorry but it's already been assigned. You can definitely create a similar issue for any other page on the site.
