### ISSUE TITLE
Search visualization

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#9]
When the search algo runs, the divs that are compared, increase in thickness. 

![IMG_20210201_123220](https://user-images.githubusercontent.com/56997545/106425308-c3034280-6489-11eb-95eb-de57324b447c.jpg)

**Comment by jainaayush01** [comment]
Yeah I have worked on it and resolved it in PR #12

**Comment by jainaayush01** [comment]
You may close this as well

**Comment by akshitadixit** [comment]
Thanks for the information.
